### ISSUE TITLE
 Module '"game/utils"' has no exported member 'getTicks'.

### ISSUE THREAD

**Issue by StreakingMan** [screepers/screeps-arena-typescript-starter#18]
I get this error when run build，haven't update typed-screeps-arena ?

**Comment by StreakingMan** [comment]
Change typed-screeps-arena to develop branch and it works. It's necessary to modify package.json devDependencies 😺

**Comment by thmsndk** [comment]
packages.json should now point to the develop  version of typed-screeps-arena until types are more stable.

https://github.com/screepers/screeps-arena-typescript-starter/commit/3f993e3053448be9a564b5b8ac2132338596516a
